#!/bin/sh

set -eu

if ! emerge -p "${@}"; then
	emerge --autounmask-write "${@}" || :

	find '/etc/portage' -name '._cfg*' | while read -r chg_config; do
		dirname="$(dirname "${chg_config}")"
		filename="$(basename "$chg_config}" | cut -d _ -f 3-)"

		mv "${chg_config}" "${dirname}/${filename}"
	done
fi

emerge "${@}"
